using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("Restfulie.NET")]
[assembly: AssemblyVersionAttribute("0.5.5.0")]
[assembly: AssemblyFileVersionAttribute("0.5.5.0")]
[assembly: AssemblyCopyrightAttribute("Copyright Mauricio Aniche 2010-2012")]
[assembly: AssemblyProductAttribute("Restfulie.NET")]
[assembly: AssemblyTrademarkAttribute("df3d98654e240cd6973a1c91b0d433df91192485")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("0.5.5.0")]
